services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=db_hostal
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"